# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4437299a2c2f5200c43bcb8a1be8cb6e4f7ebcab6b26a4e43dd7ac4b3e4e7edc94ca2bbb08d916f12770ed15087bcc4a1d34df522461ccf8d44cf0af6afa1f9

test:
  secret_key_base: 381639de51c115ca2ccc69e5afa2e2e3ce018af2adb6737405ae729e0334b7921a38fff5ffdeea4527e538add15d3c0821063671bf95a839e8248706b3f1d499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
